BDS-InfoWeb/InfoWebApp/Backup1/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LiveTile.Models
{
    public class Menu
    {
        public Menu()
        {
            MenuItems = new List<MenuItem>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public List<MenuItem> MenuItems { get; set; }
    }
}

BDS-InfoWeb/InfoWebApp/Backup1/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LiveTile.Models;

namespace LiveTile.Controllers
{
    public class MenuController : Controller
    {
        private LiveTileContext db = new LiveTileContext();

        //
        // GET: /Menu/

        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        //
        // GET: /Menu/Details/5

        public ActionResult Details(int id = 0)
        {
            Menu menu = db.Menus.Include("MenuItems").Single<Menu>(m => m.Id == id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        //
        // GET: /Menu/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Menu/Create

        [HttpPost]
        public ActionResult Create(Menu menu)
        {
            if (ModelState.IsValid)
            {
                // TODO: Disabled to prevent XSS attacks
                //db.Menus.Add(menu);
                //db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(menu);
        }

        //
        // GET: /Menu/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        //
        // POST: /Menu/Edit/5

        [HttpPost]
        public ActionResult Edit(Menu menu)
        {
            if (ModelState.IsValid)
            {
                if (!IsAdminMenu(menu))
                {
                    // TODO: Disabled to prevent XSS attacks on Demo
                    //db.Entry(menu).State = EntityState.Modified;
                    //db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        //This is a hack to prevent script kiddie hackers,
        //from deleting the Main Menus in the Demo Site
        //Either remove this check or use it for something
        //more useful in your application
        private bool IsAdminMenu(Menu menu)
        {
            return (menu.Name == "Home" || menu.Name == "Menus");
        }

        //
        // GET: /Menu/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        //
        // POST: /Menu/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            // TODO: Disabled to prevent XSS Attacks
            //Menu menu = db.Menus.Include("MenuItems").Single<Menu>(m => m.Id == id);
            //db.Menus.Remove(menu);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BDS-InfoWeb/InfoWebApp/Backup1/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LiveTile.Models;

namespace LiveTile.Controllers
{
    public class MenuItemController : Controller
    {
        private LiveTileContext db = new LiveTileContext();

        //
        // GET: /MenuItem/

        public ActionResult Index()
        {
            return View(db.MenuItems.ToList());
        }

        //
        // GET: /MenuItem/Details/5

        public ActionResult Details(int id = 0)
        {
            MenuItem menuitem = db.MenuItems.Find(id);
            if (menuitem == null)
            {
                return HttpNotFound();
            }
            return View(menuitem);
        }

        //
        // GET: /MenuItem/Create

        public ActionResult Create(int parentMenuId)
        {
            Menu menu = db.Menus.Single<Menu>(m => m.Id == parentMenuId);
            return View(new MenuItem { ParentMenu = menu });
        }

        //
        // POST: /MenuItem/Create

        [HttpPost]
        public ActionResult Create(int parentMenuId, MenuItem menuitem)
        {
            if (ModelState.IsValid)
            {
                // TODO: Uncomment the code below
                //Menu menu = db.Menus.Single<Menu>(m => m.Id == parentMenuId);
                //menuitem.ParentMenu = menu;
                //db.MenuItems.Add(menuitem);
                //db.SaveChanges();
                return RedirectToAction("Details", "Menu", new { id = parentMenuId });
            }

            return View(menuitem);
        }

        //
        // GET: /MenuItem/Edit/5

        public ActionResult Edit(int id = 0)
        {
            MenuItem menuitem = db.MenuItems.Find(id);
            if (menuitem == null)
            {
                return HttpNotFound();
            }
            return View(menuitem);
        }

        //
        // POST: /MenuItem/Edit/5

        [HttpPost]
        public ActionResult Edit(int parentMenuId, MenuItem menuitem)
        {
            if (ModelState.IsValid)
            {
                // TODO: Uncomment the code below
                //db.Entry(menuitem).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Details", "Menu", new { id = parentMenuId });
            }
            return View(menuitem);
        }

        //
        // GET: /MenuItem/Delete/5

        public ActionResult Delete(int id = 0)
        {
            MenuItem menuitem = db.MenuItems.Find(id);
            if (menuitem == null)
            {
                return HttpNotFound();
            }
            return View(menuitem);
        }

        //
        // POST: /MenuItem/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int parentMenuId, int id)
        {
            //TODO : Uncomment the code below
            //MenuItem menuitem = db.MenuItems.Find(id);
            //db.MenuItems.Remove(menuitem);
            //db.SaveChanges();
            return RedirectToAction("Details", "Menu", new { id = parentMenuId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BDS-InfoWeb/InfoWebApp/Backup1/Views/Menu/Create.cshtml
@model LiveTile.Models.Menu

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Menu</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BDS-InfoWeb/InfoWebApp/Backup1/Views/Menu/Delete.cshtml
@model LiveTile.Models.Menu

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Menu</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

BDS-InfoWeb/InfoWebApp/Backup1/Views/Menu/Details.cshtml
@model LiveTile.Models.Menu
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>
    Details</h2>
<fieldset>
    <legend>Menu</legend>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    <fieldset>
        @if (Model.MenuItems != null && Model.MenuItems.Count > 0)
        {
            <legend>Menu Items</legend>
            foreach (var item in Model.MenuItems)
            {
            <div style="border: solid 1px #F0F0F0; margin: 2px">
                <div class="comment-author">
                    Text: @item.Name
                </div>
                <div class="comment-message">
                    Action: @item.ActionName
                </div>
                <div class="comment-message">
                    Controller: @item.ControllerName
                </div>
                <div class="comment-message">
                    Url: @item.Url
                </div>
                <p>
                    @Html.ActionLink("Edit", "Edit", "MenuItem", 
                    new { parentMenuId = Model.Id, id = item.Id }, null)
                    |
                    @Html.ActionLink("Delete", "Delete", "MenuItem", 
                    new { parentMenuId = Model.Id, id = item.Id }, null)
                </p>
            </div>
            }
        }
    </fieldset>
    <div id="addMenuItem" style="display: inline;">
        <div>
            @Html.ActionLink("Add Menu Item", "Create", "MenuItem", 
            new { parentMenuId = Model.Id }, null)
        </div>
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BDS-InfoWeb/InfoWebApp/Backup1/Views/Menu/Edit.cshtml
@model LiveTile.Models.Menu

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Menu</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BDS-InfoWeb/InfoWebApp/Backup1/Views/Menu/Index.cshtml
@model IEnumerable<LiveTile.Models.Menu>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>